### ISSUE TITLE
Allow greater zoom levels

### ISSUE THREAD

**Issue by nicolasmaia** [Rudloff/openvegemap-cordova#3]
Many places have very few veggie options, so it's useful to be able to look at areas from a bigger distance.

**Comment by Rudloff** [comment]
15 is the minimum zoom recommended by [leaflet-overpass-layer](https://github.com/GuillaumeAmat/leaflet-overpass-layer) (the library used to retrieve OSM data).
The problem is that the Overpass API is quite slow so allowing lower zoom levels can make queries take a really long time in cities with a lot of vegetarian places.

Would a preference that allows you to set this value manually be OK for you?

**Comment by nicolasmaia** [comment]
At least having a preference like that would definitely help, thanks!

**Comment by Rudloff** [comment]
I did some tests and requests at a 13 zoom level still work correctly.

The change will be in the next release. If it is still not enough for you, I will add a preference.
